### ISSUE TITLE
PyPI has not the latest version

### ISSUE THREAD

**Issue by r0f1** [pmorissette/ffn#96] opened 2020-04-12 19:22 UTC
Hi,
PyPI has not the latest version. I get an error in the function `display_month_returns()`, because it uses the old `.ix[]` accessor of pandas. Looking at the code on Github, it seems that the issue was fixed already. 

My remedy: Installing ffn from directly from Github using `pip install --upgrade git+https://github.com/pmorissette/ffn.git`.

Best, Flo

**Comment by y26805** [comment] 2020-05-03 06:57
looks like a duplicate of https://github.com/pmorissette/ffn/issues/89

apparently the version on Windows works fine, but for Mac/Linux PIP does not offer the latest version.
thanks for adding the git command to install from source!

**Comment by timkpaine** [comment] 2020-11-21 22:22
closing, will do a release in the nearish future. Feel free to use an older version of pandas in the mean time.

**Closed by timkpaine** 2020-11-21 22:22 UTC
